config/routes.rb
MusicRating::Application.routes.draw do
  resources :music_rating_services

  resources :login_pages

  resources :stores

  resources :users

end

app/models/login_page.rb
class LoginPage < ActiveRecord::Base
  attr_accessible :user_name, :user_pwd
end

app/models/music_rating_service.rb
class MusicRatingService < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/store.rb
class Store < ActiveRecord::Base
  #just adding a comment to test out github rubymine xnection
  attr_accessible(:merchant_account_id, :store_loc, :store_name)

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :account_id, :name, :store_id
  
  validates :name, :presence => true
  validates :account_id, :presence => true
  belongs_to :store

  delegate(:store_name, to: :store, allow_nil: true)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/login_pages_controller.rb
class LoginPagesController < ApplicationController
  # GET /login_pages
  # GET /login_pages.json
  

  # GET /login_pages/new
  # GET /login_pages/new.json
  def new
    @login_page = LoginPage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @login_page }
    end
  end

 def create    
      #in here is where i want to get the id from the login page and set that as the session's id
      
     # @users do |aUser|   
      #    if  aUser.userName == :user_name
      #       user_id = aUser.id
      #     end  
      #  end

      #  session[:current_user_id] = user.id
      #      # redirect_to root_url
 end

end

app/controllers/music_rating_services_controller.rb
class MusicRatingServicesController < ApplicationController
  # GET /music_rating_services
  # GET /music_rating_services.json
  def index
    @music_rating_services = MusicRatingService.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @music_rating_services }
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stores }
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @store = Store.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/new
  # GET /stores/new.json
  def new
    @store = Store.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/1/edit
  def edit
    @store = Store.find(params[:id])
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(params[:store])

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render json: @store, status: :created, location: @store }
      else
        format.html { render action: "new" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stores/1
  # PUT /stores/1.json
  def update
    @store = Store.find(params[:id])

    respond_to do |format|
      if @store.update_attributes(params[:store])
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_pages_helper.rb
module LoginPagesHelper
end

app/helpers/music_rating_services_helper.rb
module MusicRatingServicesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicRating</title>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Music Rating</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Users", users_path%></li>
          <li><%= link_to "Stores", stores_path%></li>
        </ul>
      </div>
    </div>
  </div>
 </div>

<div class="container">    
	<div class="row">
      <div class="span9"><%= yield %></div>
        <div class="span3">
                <h2>About Us</h2>
            All about us....
            </div>
        </div>
    </div>
</body>
</html>

app/views/login_pages/_form.html.erb
<%= form_for(@login_page) do |f| %>
  <% if @login_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login_page.errors.count, "error") %> prohibited this login_page from being saved:</h2>

      <ul>
      <% @login_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :user_pwd %><br />
    <%= f.text_field :user_pwd %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/login_pages/_new_form.html.erb
<%= form_for(@login_page) do |f| %>
  <% if @login_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login_page.errors.count, "error") %> prohibited this login_page from being saved:</h2>

      <ul>
      <% @login_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :user_pwd %><br />
    <%= f.text_field :user_pwd %>
  </div>
  <div class="actions">  
    <%= f.submit "Login" %>
  </div>
<% end %>                            

app/views/login_pages/new.html.erb
<h2>Login</h2>

<%= render 'new_form' %>

app/views/music_rating_services/index.html.erb
<h2>Music Rating Service</h2>



<%= link_to 'Login to Service', new_login_page_path %>

app/views/stores/_form.html.erb
<%= form_for @store, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :store_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :store_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :merchant_account_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :merchant_account_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :store_loc, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :store_loc, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                stores_path, :class => 'btn' %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<%- model_class = Store -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/stores/index.html.erb
<%- model_class = Store -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <!--<th><%= model_class.human_attribute_name(:id) %></th>-->
      <th><%= model_class.human_attribute_name(:store_name) %></th>
      <th><%= model_class.human_attribute_name(:merchant_account_id) %></th>
      <th><%= model_class.human_attribute_name(:store_loc) %></th>
      <!--<th><%= model_class.human_attribute_name(:created_at) %></th>-->
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <!--<td><%= link_to store.id, store_path(store) %></td>-->
        <td><%= store.store_name %></td>
        <td><%= store.merchant_account_id %></td>
        <td><%= store.store_loc %></td>
        <!--<td><%=l store.created_at %></td>-->
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_store_path(store), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      store_path(store),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_store_path,
            :class => 'btn btn-primary' %>

app/views/stores/new.html.erb
<%- model_class = Store -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/stores/show.html.erb
<%- model_class = Store -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:store_name) %>:</strong></dt>
  <dd><%= @store.store_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:merchant_account_id) %>:</strong></dt>
  <dd><%= @store.merchant_account_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:store_loc) %>:</strong></dt>
  <dd><%= @store.store_loc %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              stores_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_store_path(@store), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              store_path(@store),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/users/_edit_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :disabled => true, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :account_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :account_id, :disabled => true, :class => 'number_field' %>
    </div>
  </div>


  <div class="control-group">
    <%= f.label :store_name, :class => 'control-label' %>
    <div class="controls">

      <%= collection_select(:user, :store_id, Store.all, :id, :store_name, options={:prompt => "select a store"}, :class => "store")%>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :account_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :account_id, :class => 'number_field' %>
    </div>
  </div>


  <div class="control-group">
    <%= f.label :store_name, :class => 'control-label' %>
    <div class="controls">

      <%= collection_select(:user, :store_id, Store.all, :id, :store_name, options={:prompt => "select a store"}, :class => "store")%>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.change_store', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'edit_form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <!--<th><%= model_class.human_attribute_name(:id) %></th>-->
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:account_id) %></th>
      <th><%= model_class.human_attribute_name(:store_name) %></th>
      <!--<th><%= model_class.human_attribute_name(:created_at) %></th>-->
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <!--<td><%= link_to user.id, user_path(user) %></td>-->
        <td><%= user.name %></td>
        <td><%= user.account_id %></td>
        <td><%= user.store_name %></td>
        <!--<td><%=l user.created_at %></td>-->
        <td>
          <%= link_to t('.edit', :default => "Change Store"),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:account_id) %>:</strong></dt>
  <dd><%= @user.account_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:store_name) %>:</strong></dt>
  <% if @user.store %>
    <dd><%= @user.store.store_name %></dd>
  <% else %>
    <dd>"no store assigned"</dd>
  <% end %>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>